services:
  app:
    build: .
    container_name: echoo-backend-services
    restart: always
    env_file:
      - .env.production
    ports:
      - '5051:5051'
    command: ['yarn', 'start']
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
